# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://drz.ac
title: DrZ.ac
subtitle: misplaced, punctuation
author: Zachary T. Harmany, PhD
simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /feed.atom
subscribe_email:
category_feeds: false
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
#markdown: kramdown
markdown: pandoc #https://github.com/fauno/jekyll-pandoc-multiple-formats YES!
pandoc:
  skip: false
  flags: '--smart --mathjax'
  #flags: '--smart --mathjax --bibliography=/Users/zac/Dropbox/BiblioDatabase/Alexandria.bib'
pygments: false # Jekyll's default Python Pygments have been replaced by pygments.rb. Set to true to use Albino + Pythong Pygments

paginate: 10          # Posts per page on the blog index
pagination_dir:  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_in_feed: false # Truncate excerpted articles in the atom feed

# My permalink / linked list settings
#permalink_label: "&#x24e9; permalink"
#permalink_label_feed: "&#x24e9; permalink"
permalink_label: "permalink"
permalink_label_feed: "permalink"
#linklog_marker: "&rarr;"
#➔
#HEAVY WIDE-HEADED RIGHTWARDS ARROW
#Unicode: U+2794, UTF-8: E2 9E 94
#➲
#CIRCLED HEAVY WHITE RIGHTWARDS ARROW
#Unicode: U+27B2, UTF-8: E2 9E B2
#linklog_marker: "&#x1f680;" # Rocket ship! Maybe once Emoji get supported in browsers other than Safari
linklog_marker: "&#x2794;" # Heavy wide arrow, so far the winner
#linklog_marker: "&#x279c;" # heavy round-tipped arrow
#linklog_marker: "&#x27B2;" # Circled heavy arrow
#linklog_marker: "&#x27A4;" # rightward arrowhead
linklog_marker_position: after
linklog_marker_position_feed: after
#standard_post_marker: "&#x24CF; " # Circled z
#standard_post_marker: "&#x1f169; " # Negative circled z
#standard_post_marker: "&#x24e9; " # circled latin small letter z, keep the space!



# Marco Arment
#permalink_label: "&infin;"
#permalink_label_feed: "&infin; Permalink"
#linklog_marker: "&rarr;"
#linklog_marker_position: after
#linklog_marker_position_feed: after
#standard_post_marker:

# John Gruber
#permalink_label: "&#9733;"
#permalink_label_feed: "&#9733;"
#linklog_marker:
#linklog_marker_position:
#linklog_marker_position_feed:
#standard_post_marker: "&#9733; " # Need the space!


titlecase: true       # Converts page and post titles to titlecase

# To change the layout's default sidebar Add a new sidebar source/_includes/sidebars/your_sidebar.html
# then make changes below, eg. post_sidebar: your_sidebar.html
blog_index_sidebar: your_blog_index_default.html
page_sidebar: page_default.html
post_sidebar: post_default.html

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Javascript social buttons often generate lots of http requests and may track your viewer's browsing history
# Show respect for privacy and bandwidth with simple links for Twitter, Facebook and Google Plus.
respectfully_social: true

# Github repositories
github_user: zharmany
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: zacharmany
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
google_plus_user:
google_plus_hidden: false
google_plus_image_size: 32

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: drzac
disqus_show_comment_count: false
disqus_developer: 0

# Google Analytics
google_analytics_tracking_id: UA-37209945-1

# Gaug.es Analytics
gauges_analytics_tracking_id:

# Facebook Like
facebook_like: false
